In [111]:
# Dependencies and Set up
import requests
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler

In [112]:
#connecting with the csv
df = pd.read_csv('Resources/crypto_data.csv')
df

Unnamed: 0        CoinName Algorithm  IsTrading ProofType  \
0            42         42 Coin    Scrypt       True   PoW/PoS   
1           365         365Coin       X11       True   PoW/PoS   
2           404         404Coin    Scrypt       True   PoW/PoS   
3           611       SixEleven   SHA-256       True       PoW   
4           808             808   SHA-256       True   PoW/PoS   
...         ...             ...       ...        ...       ...   
1247        XBC     BitcoinPlus    Scrypt       True       PoS   
1248       DVTC      DivotyCoin    Scrypt      False   PoW/PoS   
1249       GIOT     Giotto Coin    Scrypt      False   PoW/PoS   
1250       OPSC  OpenSourceCoin   SHA-256      False   PoW/PoS   
1251       PUNK       SteamPunk       PoS      False       PoS   

      TotalCoinsMined TotalCoinSupply  
0        4.199995e+01              42  
1                 NaN      2300000000  
2        1.055185e+09       532000000  
3                 NaN          611000  
4        0.000000e+00               0  
...               ...             ...  
1247     1.283270e+05         1000000  
1248     2.149121e+07       100000000  
1249              NaN       233100000  
1250              NaN        21000000  
1251              NaN        40000000  

[1252 rows x 7 columns]

In [113]:
df.shape

(1252, 7)

In [114]:
# filtering the data to only true values
df = df.loc[df['IsTrading']==True]
df

Unnamed: 0     CoinName    Algorithm  IsTrading ProofType  \
0            42      42 Coin       Scrypt       True   PoW/PoS   
1           365      365Coin          X11       True   PoW/PoS   
2           404      404Coin       Scrypt       True   PoW/PoS   
3           611    SixEleven      SHA-256       True       PoW   
4           808          808      SHA-256       True   PoW/PoS   
...         ...          ...          ...        ...       ...   
1243       SERO   Super Zero       Ethash       True       PoW   
1244        UOS          UOS      SHA-256       True      DPoI   
1245        BDX       Beldex  CryptoNight       True       PoW   
1246        ZEN      Horizen     Equihash       True       PoW   
1247        XBC  BitcoinPlus       Scrypt       True       PoS   

      TotalCoinsMined TotalCoinSupply  
0        4.199995e+01              42  
1                 NaN      2300000000  
2        1.055185e+09       532000000  
3                 NaN          611000  
4        0.000000e+00               0  
...               ...             ...  
1243              NaN      1000000000  
1244              NaN      1000000000  
1245     9.802226e+08      1400222610  
1246     7.296538e+06        21000000  
1247     1.283270e+05         1000000  

[1144 rows x 7 columns]

In [115]:
df.shape

(1144, 7)

In [116]:
df.isnull().sum()

Unnamed: 0           0
CoinName             0
Algorithm            0
IsTrading            0
ProofType            0
TotalCoinsMined    459
TotalCoinSupply      0
dtype: int64

In [117]:
df = df.dropna()
df

Unnamed: 0     CoinName    Algorithm  IsTrading ProofType  \
0            42      42 Coin       Scrypt       True   PoW/PoS   
2           404      404Coin       Scrypt       True   PoW/PoS   
4           808          808      SHA-256       True   PoW/PoS   
5          1337    EliteCoin          X13       True   PoW/PoS   
7           BTC      Bitcoin      SHA-256       True       PoW   
...         ...          ...          ...        ...       ...   
1238       ZEPH       ZEPHYR      SHA-256       True      DPoS   
1242        GAP      Gapcoin       Scrypt       True   PoW/PoS   
1245        BDX       Beldex  CryptoNight       True       PoW   
1246        ZEN      Horizen     Equihash       True       PoW   
1247        XBC  BitcoinPlus       Scrypt       True       PoS   

      TotalCoinsMined TotalCoinSupply  
0        4.199995e+01              42  
2        1.055185e+09       532000000  
4        0.000000e+00               0  
5        2.927942e+10    314159265359  
7        1.792718e+07        21000000  
...               ...             ...  
1238     2.000000e+09      2000000000  
1242     1.493105e+07       250000000  
1245     9.802226e+08      1400222610  
1246     7.296538e+06        21000000  
1247     1.283270e+05         1000000  

[685 rows x 7 columns]

In [118]:
labels = df['CoinName']
labels

0           42 Coin
2           404Coin
4               808
5         EliteCoin
7           Bitcoin
           ...     
1238         ZEPHYR
1242        Gapcoin
1245         Beldex
1246        Horizen
1247    BitcoinPlus
Name: CoinName, Length: 685, dtype: object

In [119]:
df = df.drop(['IsTrading', 'CoinName'], axis=1)
df

Unnamed: 0    Algorithm ProofType  TotalCoinsMined TotalCoinSupply
0            42       Scrypt   PoW/PoS     4.199995e+01              42
2           404       Scrypt   PoW/PoS     1.055185e+09       532000000
4           808      SHA-256   PoW/PoS     0.000000e+00               0
5          1337          X13   PoW/PoS     2.927942e+10    314159265359
7           BTC      SHA-256       PoW     1.792718e+07        21000000
...         ...          ...       ...              ...             ...
1238       ZEPH      SHA-256      DPoS     2.000000e+09      2000000000
1242        GAP       Scrypt   PoW/PoS     1.493105e+07       250000000
1245        BDX  CryptoNight       PoW     9.802226e+08      1400222610
1246        ZEN     Equihash       PoW     7.296538e+06        21000000
1247        XBC       Scrypt       PoS     1.283270e+05         1000000

[685 rows x 5 columns]

In [120]:
#resetting the index column 
df = df.set_index('Unnamed: 0')
df

Algorithm ProofType  TotalCoinsMined TotalCoinSupply
Unnamed: 0                                                        
42               Scrypt   PoW/PoS     4.199995e+01              42
404              Scrypt   PoW/PoS     1.055185e+09       532000000
808             SHA-256   PoW/PoS     0.000000e+00               0
1337                X13   PoW/PoS     2.927942e+10    314159265359
BTC             SHA-256       PoW     1.792718e+07        21000000
...                 ...       ...              ...             ...
ZEPH            SHA-256      DPoS     2.000000e+09      2000000000
GAP              Scrypt   PoW/PoS     1.493105e+07       250000000
BDX         CryptoNight       PoW     9.802226e+08      1400222610
ZEN            Equihash       PoW     7.296538e+06        21000000
XBC              Scrypt       PoS     1.283270e+05         1000000

[685 rows x 4 columns]

In [121]:
df.shape

(685, 4)

In [122]:
#filtering for values grater than 0
df = df[df['TotalCoinsMined'] > 0]
df

Algorithm ProofType  TotalCoinsMined TotalCoinSupply
Unnamed: 0                                                        
42               Scrypt   PoW/PoS     4.199995e+01              42
404              Scrypt   PoW/PoS     1.055185e+09       532000000
1337                X13   PoW/PoS     2.927942e+10    314159265359
BTC             SHA-256       PoW     1.792718e+07        21000000
ETH              Ethash       PoW     1.076842e+08               0
...                 ...       ...              ...             ...
ZEPH            SHA-256      DPoS     2.000000e+09      2000000000
GAP              Scrypt   PoW/PoS     1.493105e+07       250000000
BDX         CryptoNight       PoW     9.802226e+08      1400222610
ZEN            Equihash       PoW     7.296538e+06        21000000
XBC              Scrypt       PoS     1.283270e+05         1000000

[532 rows x 4 columns]

In [123]:
df.shape

(532, 4)

In [124]:
#converting into dummies Algorithm and ProofType columns
X = pd.get_dummies(df, columns=['Algorithm', 'ProofType'])
X

TotalCoinsMined TotalCoinSupply  Algorithm_1GB AES Pattern Search  \
Unnamed: 0                                                                      
42             4.199995e+01              42                                 0   
404            1.055185e+09       532000000                                 0   
1337           2.927942e+10    314159265359                                 0   
BTC            1.792718e+07        21000000                                 0   
ETH            1.076842e+08               0                                 0   
...                     ...             ...                               ...   
ZEPH           2.000000e+09      2000000000                                 0   
GAP            1.493105e+07       250000000                                 0   
BDX            9.802226e+08      1400222610                                 0   
ZEN            7.296538e+06        21000000                                 0   
XBC            1.283270e+05         1000000                                 0   

            Algorithm_536  Algorithm_Argon2d  Algorithm_BLAKE256  \
Unnamed: 0                                                         
42                      0                  0                   0   
404                     0                  0                   0   
1337                    0                  0                   0   
BTC                     0                  0                   0   
ETH                     0                  0                   0   
...                   ...                ...                 ...   
ZEPH                    0                  0                   0   
GAP                     0                  0                   0   
BDX                     0                  0                   0   
ZEN                     0                  0                   0   
XBC                     0                  0                   0   

            Algorithm_Blake  Algorithm_Blake2S  Algorithm_Blake2b  \
Unnamed: 0                                                          
42                        0                  0                  0   
404                       0                  0                  0   
1337                      0                  0                  0   
BTC                       0                  0                  0   
ETH                       0                  0                  0   
...                     ...                ...                ...   
ZEPH                      0                  0                  0   
GAP                       0                  0                  0   
BDX                       0                  0                  0   
ZEN                       0                  0                  0   
XBC                       0                  0                  0   

            Algorithm_C11  ...  ProofType_PoW/PoS  ProofType_PoW/PoS   \
Unnamed: 0                 ...                                          
42                      0  ...                  1                   0   
404                     0  ...                  1                   0   
1337                    0  ...                  1                   0   
BTC                     0  ...                  0                   0   
ETH                     0  ...                  0                   0   
...                   ...  ...                ...                 ...   
ZEPH                    0  ...                  0                   0   
GAP                     0  ...                  1                   0   
BDX                     0  ...                  0                   0   
ZEN                     0  ...                  0                   0   
XBC                     0  ...                  0                   0   

            ProofType_PoW/PoW  ProofType_PoW/nPoS  ProofType_Pos  \
Unnamed: 0                                                         
42                          0                   0              0   
404                  

In [125]:
X.shape

(532, 98)

In [126]:
# Create a scaler to standardize the data
from sklearn.preprocessing import StandardScaler

In [127]:
# Train the scaler with the training data.
df_scaled = StandardScaler().fit_transform(X)
print(df_scaled)

[[-0.11710817 -0.1528703  -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 [-0.09396955 -0.145009   -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 [ 0.52494561  4.48942416 -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 ...
 [-0.09561336 -0.13217937 -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 [-0.11694817 -0.15255998 -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]
 [-0.11710536 -0.15285552 -0.0433963  ... -0.0433963  -0.0433963
  -0.0433963 ]]


In [128]:
from sklearn.decomposition import PCA

In [129]:
# Initialize PCA model
pca = PCA(n_components=0.99)

# Get two principal components for the iris data.
df_pca = pca.fit_transform(df_scaled)
df_pca

array([[-0.33509881,  1.03218907, -0.59071344, ...,  0.13391619,
        -0.11593793,  0.00934363],
       [-0.31843395,  1.03233143, -0.59112555, ...,  0.13399077,
        -0.11564619,  0.00918792],
       [ 2.30546811,  1.65638302, -0.68361667, ..., -0.07341934,
         0.17914389, -1.41905933],
       ...,
       [ 0.32434854, -2.31230764,  0.42151537, ...,  0.23019201,
        -0.01101053,  0.47286829],
       [-0.14936365, -2.04933553,  0.41296826, ...,  0.35568904,
         0.08258903, -0.07056385],
       [-0.2899575 ,  0.82119451, -0.27632685, ...,  1.03190166,
        -0.05476628, -0.9014263 ]])

In [130]:
df_pca.shape

(532, 86)

In [131]:
pca = PCA(n_components=3)

# Get two principal components for the iris data.
df_pca_cp3 = pca.fit_transform(df_scaled)
df_pca_cp3

array([[-0.34477777,  0.97017334, -0.44386287],
       [-0.32812607,  0.97035238, -0.44436587],
       [ 2.32088215,  1.69238566, -0.51828712],
       ...,
       [ 0.33067228, -2.24552335,  0.32175101],
       [-0.1307731 , -2.04757181,  0.37616566],
       [-0.32156822,  0.649268  , -0.18619199]])

In [132]:
# Transform PCA data to a DataFrame
df_pca_cp3 = pd.DataFrame(
    data= df_pca_cp3, columns=["principal component 1", "principal component 2","principal component 3" ]
)
df_pca_cp3.head()

principal component 1  principal component 2  principal component 3
0              -0.344778               0.970173              -0.443863
1              -0.328126               0.970352              -0.444366
2               2.320882               1.692386              -0.518287
3              -0.137214              -1.275804               0.166677
4              -0.136430              -1.992697               0.263953

In [133]:
#check what the values mean 
print(pca.explained_variance_)

[2.74201562 2.0981969  2.00998881]


In [134]:
pca.explained_variance_ratio_

array([0.02792716, 0.02136993, 0.02047154])

In [135]:
from sklearn.manifold import TSNE

In [136]:
tsne = TSNE(learning_rate=35)

In [137]:
tsne_features = tsne.fit_transform(df_pca_cp3)

In [141]:
data_scaled  = pd.DataFrame(df_scaled)
data_scaled

0         1         2         3         4        5         6   \
0   -0.117108 -0.152870 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   
1   -0.093970 -0.145009 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   
2    0.524946  4.489424 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   
3   -0.116715 -0.152560 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   
4   -0.114747 -0.152870 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   
..        ...       ...       ...       ...       ...      ...       ...   
527 -0.073251 -0.123317 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   
528 -0.116781 -0.149176 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   
529 -0.095613 -0.132179 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   
530 -0.116948 -0.152560 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   
531 -0.117105 -0.152856 -0.043396 -0.043396 -0.043396 -0.06143 -0.075307   

           7        8        9   ...        88        89        90        91  \
0   -0.043396 -0.06143 -0.06143  ...  1.422226 -0.043396 -0.043396 -0.043396   
1   -0.043396 -0.06143 -0.06143  ...  1.422226 -0.043396 -0.043396 -0.043396   
2   -0.043396 -0.06143 -0.06143  ...  1.422226 -0.043396 -0.043396 -0.043396   
3   -0.043396 -0.06143 -0.06143  ... -0.703123 -0.043396 -0.043396 -0.043396   
4   -0.043396 -0.06143 -0.06143  ... -0.703123 -0.043396 -0.043396 -0.043396   
..        ...      ...      ...  ...       ...       ...       ...       ...   
527 -0.043396 -0.06143 -0.06143  ... -0.703123 -0.043396 -0.043396 -0.043396   
528 -0.043396 -0.06143 -0.06143  ...  1.422226 -0.043396 -0.043396 -0.043396   
529 -0.043396 -0.06143 -0.06143  ... -0.703123 -0.043396 -0.043396 -0.043396   
530 -0.043396 -0.06143 -0.06143  ... -0.703123 -0.043396 -0.043396 -0.043396   
531 -0.043396 -0.06143 -0.06143  ... -0.703123 -0.043396 -0.043396 -0.043396   

           92        93        94        95        96        97  
0   -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  
1   -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  
2   -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  
3   -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  
4   -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  
..        ...       ...       ...       ...       ...       ...  
527 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  
528 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  
529 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  
530 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  
531 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396 -0.043396  

[532 rows x 98 columns]

In [140]:
tsne_features


array([[-13.815564 ,  -3.5049412],
       [-10.690142 ,  -9.830793 ],
       [ -1.9968983, -15.387393 ],
       ...,
       [ -4.4028187,  18.698605 ],
       [ -9.84779  ,  22.61874  ],
       [  4.370839 ,  -5.0893235]], dtype=float32)

In [139]:
# Prepare to plot the dataset

# The first column of transformed features
data_scaled['x'] = tsne_features[:,0]

# The second column of transformed features
df2['y'] = tsne_features[:,1]

NameError: name 'df2' is not defined